//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StitchingType
    {
        public StitchingType()
        {
            this.StitchingOrders = new HashSet<StitchingOrder>();
        }
    
        public short Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ICollection<StitchingOrder> StitchingOrders { get; set; }
    }
}
