//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StitchingOrder
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public short StitchingTypeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual User AssignedToUser { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual StitchingType StitchingType { get; set; }
    }
}
